version: '3'

services:
  postgres:
    build: .docker/postgres
    container_name: postgres_blog
    restart: always
    tty: true
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - .docker/dbdata:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - net

  redis:
    image: redis:alpine
    restart: always
    container_name: redis_blog
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - net

  api:
    depends_on:
      - postgres
      - redis
      - migration
    build:
      dockerfile: .docker/api/Dockerfile
      context: .
    container_name: api_blog
    image: gustavoteixeira8/api_blog
    restart: always
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env
    networks:
      - net

  migration:
    container_name: migration_blog
    build:
      dockerfile: .docker/migration/Dockerfile
      context: .
    tty: true
    env_file: .env
    image: gustavoteixeira8/migration_blog
    depends_on:
      - postgres
    networks:
      - net

networks:
  net:
    driver: bridge
