version: '3'

services:
  postgres:
    build: .docker/postgres
    container_name: postgres_blog
    restart: always
    tty: true
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - .docker/dbdata:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - net

  redis:
    image: redis:alpine
    restart: always
    container_name: redis_blog
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_blog
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 3001:80
    depends_on:
      - postgres

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight_blog
    restart: always
    depends_on:
      - redis
    ports:
      - 3002:8001
    networks:
      - net



networks:
  net:
    driver: bridge
