version: '3'

services:
  postgres:
    build: .docker/postgres
    container_name: postgres_blog
    restart: always
    tty: true
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - .docker/dbdata:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - blog_api

  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis_blog
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - blog_api

networks:
  blog_api:
    driver: bridge
