export const sanitizeConfig = {
  allowedSchemes: ['https', 'mailto'],
  allowedAttributes: {
    address: ['style', 'class', 'id'],
    article: ['style', 'class', 'id'],
    aside: ['style', 'class', 'id'],
    footer: ['style', 'class', 'id'],
    header: ['style', 'class', 'id'],
    h1: ['style', 'class', 'id'],
    h2: ['style', 'class', 'id'],
    h3: ['style', 'class', 'id'],
    h4: ['style', 'class', 'id'],
    h5: ['style', 'class', 'id'],
    h6: ['style', 'class', 'id'],
    hgroup: ['style', 'class', 'id'],
    nav: ['style', 'class', 'id'],
    section: ['style', 'class', 'id'],
    blockquote: ['style', 'class', 'id'],
    dd: ['style', 'class', 'id'],
    div: ['style', 'class', 'id'],
    dl: ['style', 'class', 'id'],
    dt: ['style', 'class', 'id'],
    figcaption: ['style', 'class', 'id'],
    figure: ['style', 'class', 'id'],
    hr: ['style', 'class', 'id'],
    li: ['style', 'class', 'id'],
    main: ['style', 'class', 'id'],
    ol: ['style', 'class', 'id'],
    p: ['style', 'class', 'id'],
    pre: ['style', 'class', 'id', 'data-mce-selected', 'contenteditable'],
    ul: ['style', 'class', 'id'],
    a: ['style', 'class', 'id', 'href', 'name', 'target'],
    abbr: ['style', 'class', 'id'],
    b: ['style', 'class', 'id'],
    bdi: ['style', 'class', 'id'],
    bdo: ['style', 'class', 'id'],
    br: ['style', 'class', 'id'],
    cite: ['style', 'class', 'id'],
    code: ['style', 'class', 'id'],
    data: ['style', 'class', 'id'],
    dfn: ['style', 'class', 'id'],
    em: ['style', 'class', 'id'],
    i: ['style', 'class', 'id'],
    kbd: ['style', 'class', 'id'],
    mark: ['style', 'class', 'id'],
    q: ['style', 'class', 'id'],
    rb: ['style', 'class', 'id'],
    rp: ['style', 'class', 'id'],
    rt: ['style', 'class', 'id'],
    rtc: ['style', 'class', 'id'],
    ruby: ['style', 'class', 'id'],
    s: ['style', 'class', 'id'],
    samp: ['style', 'class', 'id'],
    small: ['style', 'class', 'id'],
    span: ['style', 'class', 'id'],
    strong: ['style', 'class', 'id'],
    sub: ['style', 'class', 'id'],
    sup: ['style', 'class', 'id'],
    time: ['style', 'class', 'id'],
    u: ['style', 'class', 'id'],
    var: ['style', 'class', 'id'],
    wbr: ['style', 'class', 'id'],
    caption: ['style', 'class', 'id'],
    col: ['style', 'class', 'id'],
    colgroup: ['style', 'class', 'id'],
    table: ['style', 'class', 'id'],
    tbody: ['style', 'class', 'id'],
    td: ['style', 'class', 'id'],
    tfoot: ['style', 'class', 'id'],
    th: ['style', 'class', 'id'],
    thead: ['style', 'class', 'id'],
    tr: ['style', 'class', 'id'],
  },
};
